apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never #Never, OnFailure, Always
  terminationGracePeriodSeconds: 10
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - "sleep"
    - "3600"