apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never #Never, OnFailure, Always
  containers:
  - name: entrypoint
    image: vinsdocker/k8s-entrypoint
    command: #we replace args here
    - "date"