apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never #Never, OnFailure, Always
  containers:
  - name: ubuntu
    image: ubuntu
    env:
     - name: "reuqest.timeout"
       value: "10ms"
     - name: "spring.profiles.active"
       value: "dev"
    args:
    - "env"