apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service
  replicas: 3
  template: 
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
        - name: "app-port"
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
      app: order-service
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: demo-pod
    image: vinsdocker/util
    ports:
    - containerPort: 80
    args:
    - "sleep"
    - "3600"