apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  annotations:
    kubernetes.io/change-cause: "deploying v1"
spec:
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: order-service
  replicas: 2
  template: 
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: vinsdocker/k8s-app:v2
        ports:
        - name: "app-port"
          containerPort: 80