
# nginx will start after 10 seconds
# livenessProbe will start after startupProbe

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: probe-demo
    image: vinsdocker/k8s-probe-demo
    startupProbe:
      httpGet:
        path: /
        port: 80
      periodSeconds: 1
      failureThreshold: 30
    livenessProbe:
      httpGet:
        path: /live.html
        port: 80
      periodSeconds: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready.html
        port: 80
      periodSeconds: 1
      failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
      app: my-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP