apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data: 
  username: YXJhZmlu
  password: MTIz

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    envFrom:
     - secretRef:
         name: app-secret
    # env: 
    # - name: "app_username"
    #   valueFrom:
    #     secretKeyRef:
    #       name: app-secret
    #       key: username
    # - name: "app_password"
    #   valueFrom:
    #     secretKeyRef:
    #       name: app-secret
    #       key: password
    args:
      - env