apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  application.properties: |
    appUrl=http://my-app-service
    timeout=30
    myKeys=fkjkjsakj
    username=arafin

---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/props
    args:
    - sleep
    - "3600"
  volumes:
  - name: config-volume
    configMap:
      name: app-properties
    # env: 
    # - name: "request.timeout"
    #   valueFrom:
    #     configMapKeyRef:
    #       name: app-properties
    #       key: timeout
    # - name: "application.url"
    #   valueFrom:
    #     configMapKeyRef:
    #       name: app-properties
    #       key: appUrl
    # envFrom:
    # - configMapRef:
    #     name: app-properties
    # args:
    #   - env