apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
  labels:
    team: team-1
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    team: team-1
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-3
  labels:
    department: department-3
    team: team-1
spec:
  containers:
  - name: nginx
    image: nginx